#!/usr/bin/env python3
"""Regenerate the stack catalogue in README.md and docs/VERSIONS.md.

Usage: python scripts/catalog.py [--check]
With --check, exits non-zero if the generated files are out of date (used in CI).
"""
import pathlib
import re
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lint import ComposeLoader  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATEGORIES = {
    "networking": "Networking & Remote Access",
    "dns": "DNS",
    "security": "Security & Identity",
    "observability": "Observability",
    "devops": "DevOps & Automation",
    "management": "Container Management",
    "databases": "Databases",
    "applications": "Applications",
}
BEGIN, END = "<!-- catalog:begin -->", "<!-- catalog:end -->"


def stacks():
    for cat in CATEGORIES:
        for d in sorted((ROOT / "stacks" / cat).glob("*/compose.yaml")):
            yield cat, d.parent


def describe(stack):
    lines = (stack / "README.md").read_text(encoding="utf-8").splitlines()
    title = next((l[2:].strip() for l in lines if l.startswith("# ")), stack.name)
    para = []
    for l in lines[lines.index(next(l for l in lines if l.startswith("# "))) + 1:]:
        if not l.strip():
            if para:
                break
            continue
        if l.startswith(("#", "|", ">", "!", "<", "```")):
            if para:
                break
            continue
        para.append(l.strip())
    desc = re.sub(r"\s+", " ", " ".join(para))
    desc = re.split(r"(?<=[.!?])\s", desc)[0]
    desc = re.sub(r"\]\((\.\./)+[^)]*\)", "]", desc).replace("[", "").replace("]", "")
    if len(desc) > 140:
        desc = desc[:137].rsplit(" ", 1)[0].rstrip(",;:") + "…"
    return title, desc


def images(stack):
    found = set()
    for f in stack.glob("compose*.yaml"):
        doc = yaml.load(f.read_text(encoding="utf-8"), Loader=ComposeLoader) or {}
        for svc in (doc.get("services") or {}).values():
            if svc.get("image"):
                found.add(svc["image"])
    return sorted(found)


def exceptions(stack):
    n = 0
    for f in stack.glob("compose*.yaml"):
        n += len(re.findall(r"HARDENING-EXCEPTION", f.read_text(encoding="utf-8")))
    return n


def build():
    out = [BEGIN, ""]
    versions = ["# Image Versions", "",
                "Generated by `scripts/catalog.py`. Renovate keeps these current.", "",
                "| Stack | Image | Tag |", "|---|---|---|"]
    total = 0
    for cat, title in CATEGORIES.items():
        rows = [(s, *describe(s)) for c, s in stacks() if c == cat]
        if not rows:
            continue
        out += [f"### {title}", "", "| Stack | Description | Exceptions |", "|---|---|:-:|"]
        for s, name, desc in rows:
            rel = s.relative_to(ROOT).as_posix()
            exc = exceptions(s)
            out.append(f"| [{name}]({rel}) | {desc} | {exc if exc else '—'} |")
            for img in images(s):
                repo, tag = img.rsplit(":", 1)
                versions.append(f"| [{s.name}](../{rel}) | `{repo}` | `{tag}` |")
            total += 1
        out.append("")
    out.append(f"_{total} stacks. **Exceptions** = documented `HARDENING-EXCEPTION`s (see each stack's Security notes)._")
    out += ["", END]
    return "\n".join(out), "\n".join(versions) + "\n"


def main(check=False):
    catalog, versions = build()
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: catalog, text, flags=re.S)
    vfile = ROOT / "docs" / "VERSIONS.md"
    if check:
        stale = new != text or not vfile.exists() or vfile.read_text(encoding="utf-8") != versions
        if stale:
            print("README.md / docs/VERSIONS.md are out of date: run python scripts/catalog.py")
        return 1 if stale else 0
    readme.write_text(new, encoding="utf-8", newline="\n")
    vfile.write_text(versions, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
